import Head from "next/head";

import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillMail,
  AiFillMediumCircle,
  AiFillCopyrightCircle,
} from "react-icons/ai";
import { TypeAnimation } from "react-type-animation";
import Image from "next/image";
import myAvatar from "../public/images/full-body-murithi.png";
import Navbar from "./components/Navbar";
import Background from "./components/Background";
const styles = {
  fontSize: "18px",
  "@media (min-width: 768px)": {
    fontSize: "28px",
  },
  "@media (min-width: 1024px)": {
    fontSize: "32px",
  },
};
export default function Home() {
  return (
    <>
      <Head>
        <title>Hope Murithi portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="px-10 text-white lg:overflow-hidden">
        <section className=" min-h-screen">
          <div>
            <Navbar />
          </div>
          <div>
            <Background />
            <div className="text-center p-10">
              <h2 className="text-6xl py-2 font-neueMachina text-white">
                Hope Murithi
              </h2>
            </div>
            <div className="flex -mt-5">
            <div className=" mx-auto bg-gradient-to-tr from-gray-800 to-yellow-600 rounded-full w-80 h-80 mt-10 overflow-hidden">
              <Image src={myAvatar} alt="Avatar" />
            </div>
            </div>
          
            <h3 className="font-neueMachina font-bold text-md py-2 text-center m-5 md:text-xl lg:text-2xl">
              <TypeAnimation
                sequence={[
                  "I am a full-stack developer with a passion for building dynamic and engaging websites. Additionally, I write on Medium about Web3 and am actively learning blockchain technology with Ethereum and Solidity. Let's work together to create the next generation of web experiences! ",
                  10000,
                ]}
                speed={60}
                style={styles}
                wrapper="span"
                repeat={Infinity}
              />
            </h3>
          </div>
          <div className="flex justify-center text-5xl gap-10 text-white py-3  mt-5">
            <a href="https://twitter.com/HoppMwenda">
              <AiFillTwitterCircle className="transform hover:text-gray-400 cursor-pointer transition duration-500 hover:scale-125" />
            </a>
            <a href="https://linkedin.com/in/hope-murithi">
              <AiFillLinkedin className="transform hover:text-gray-400 transition cursor-pointer duration-500 hover:scale-125" />
            </a>
            <a href="mailto:hoppmurithi@gmail.com">
              {" "}
              <AiFillMail className="transform hover:text-gray-400 transition cursor-pointer duration-500 hover:scale-125" />
            </a>
            <a href="https://medium.com/@hoppmurithi">
              <AiFillMediumCircle className="transform hover:text-gray-400 cursor-pointer transition duration-500 hover:scale-125" />
            </a>
          </div>
        </section>
        <div className="flex justify-center items-center text-lg font-burtons">
          <AiFillCopyrightCircle /> {new Date().getFullYear()}
        </div>
      </main>
    </>
  );
}
