import Head from 'next/head'
import {BsFillMoonStarsFill} from 'react-icons/bs'



export default function Home() {
  return (
    <>
      <Head>
        <title>Hope Murithi portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section className='bg-blue-700 min-h-screen'>
  <nav>
    <h1>Hope Murithi</h1>
    <ul>
      <li>
        <BsFillMoonStarsFill/>
      </li>
      <li><a href='#'>Resume</a></li>
    </ul>
  </nav>
        </section>
      </main>
    </>
  )
}
