import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillMail,
  AiFillGithub,
} from "react-icons/ai";
import { TypeAnimation } from "react-type-animation";
import { motion, useScroll, useTransform } from "framer-motion";

import Image from "next/image";
import myAvatar from "../public/images/full-body-murithi.png";
import design from "../public/images/design.jpg";
import development from "../public/images/development.jpg";
import maintenance from "../public/images/maintenance.jpg";
import snappy from "../public/images/snappy.png";
import weather from "../public/images/Weatherapp.png";
import data from "../public/images/data.png";

interface ParallaxProps {
  children: string;
  baseVelocity: number;
}

function ParallaxText({ children, baseVelocity = 100 }: ParallaxProps) {
  const { scrollY } = useScroll();
  const y = useTransform(scrollY, (value) => value * -baseVelocity);

  return (
    <div className="parallax">
      <motion.div className="scroller" style={{ y }}>
        {Array(10)
          .fill(children)
          .map((text, i) => (
            <span key={i}>{text} </span>
          ))}
      </motion.div>
    </div>
  );
}

export default function Home() {
  return (
    <>
      <motion.div
        className="box"
        whileHover={{ scale: 1.1 }}
        transition={{ type: "spring", stiffness: 400, damping: 10 }}
      />
      <Head>
        <title>Hope Murithi portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-[url(/images/circle-scatter2.svg)] bg-cover bg-no-repeat px-10 text-black">
        <section className=" min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-burtons">Hope Murithi</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill className="cursor-pointer text-2xl" />
              </li>
              <li>
                <a
                  href="#"
                  className="bg-gradient-to-tr from-gray-800 to-yellow-600 text-white px-4 py-2 rounded-full ml-8"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="">
            <div className="text-center p-10">
              <h2 className="text-6xl py-2 font-burtons text-yellow-600">
                Hope Murithi
              </h2>
              <h3 className="font-burtons md:text-lg font-bold text-md py-2">
                <TypeAnimation
                  sequence={[
                    "Software engineer",
                    1000,
                    "Web developer",
                    1000,
                    "Competitive programmer",
                    1000,
                    "Always learning",
                    1000,
                  ]}
                  speed={50}
                  style={{ fontSize: "18px" }}
                  wrapper="span"
                  repeat={Infinity}
                />
              </h3>
              <p className="text-md md:text-lg text-gray-700 leading-8">
                Creating user-centered solutions using emerging web technologies
                and tools.Hit me up; lets connect
              </p>
            </div>
          </div>

          <div className="flex justify-center text-5xl gap-10 text-gray-700 py-3 cursor-pointer">
            <a href="https://twitter.com/HoppMwenda">
              <AiFillTwitterCircle />
            </a>
            <a href="https://linkedin.com/in/hope-murithi">
              <AiFillLinkedin />
            </a>
            <a href="mailto:hoppmurithi@gmail.com">
              {" "}
              <AiFillMail />
            </a>
            <a href="https://github.com/Hopp-Murithi">
              <AiFillGithub />
            </a>
          </div>
          <div className="relative mx-auto bg-gradient-to-tr from-gray-800 to-yellow-600 rounded-full w-80 h-80 mt-10 overflow-hidden">
            <Image src={myAvatar} alt="Avatar" />
          </div>
        </section>
        <section>
          <div>
            <h3 className=" flex justify-center items-center text-3xl py-1 mt-5">
              What I do
            </h3>
            <p className="text-md text-gray-700 leading-8">
              I design and develop secure,user-friendly and scalable websites
              and web apps with appealing UIs, using top notch tools and
              technologies for both businesses and consumer use. I am also a
              budding contributor to open source projects
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image src={design} alt="design" width={250} height={250} />
              <h3 className="py-4 text-yellow-600 text-lg pb-2 pt-8 font-medium">
                Elegant designs
              </h3>
              <p className="py-2">
                Creating beautiful models,sitemaps,wireframes and
                user/architectural designs using tools like photoshop and figma
              </p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image
                src={development}
                alt="development"
                width={250}
                height={250}
              />
              <h3 className="py-4 text-yellow-600 text-lg pb-2 pt-8 font-medium">
                Agile Development
              </h3>
              <p className="py-2">
                Writing and testing code with expert teams in short sprints to
                ensure attention to detail as well as the stakeholder's
                involvement in the building process
              </p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image src={maintenance} alt="design" width={250} height={250} />
              <h3 className="py-4 text-yellow-600 text-lg pb-2 pt-8 font-medium">
                Maintenance
              </h3>
              <p className="py-2">
                Wheather it's bug fixes,code refactoring,introduction of new
                features to an existing software or redesigning, I deliver.
              </p>
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="flex justify-center items-center text-3xl pb-5 py-1 mt-5">
              Projects
            </h3>
            <div className="lg:flex gap-10">
              <div className="text-center  p-10  my-10  flex-1  rounded overflow-hidden shadow-lg  dark:bg-white mb-4">
                <Image className="w-full" src={snappy} alt="Snappy" />
                <div className="px-6 py-4">
                  <div className="flex items-center text-yellow-600 justify-center font-bold font-burtons text-xl mb-2">
                    Snappy
                  </div>
                  <p className="text-gray-700 text-base">
                    A mock social media application made with reactjs and
                    tailwind for the frontend and{" "}
                    <a
                      href="https://www.sanity.io/"
                      className="text-red-500 underline"
                    >
                      Sanity.io
                    </a>
                    , a headless CMS for content driven sites.It allows users
                    login using their google account and
                    upload,save,download,scroll through catchy pictures posted
                    by other users and comment
                  </p>
                </div>
                <div className="px-6 pt-4 pb-2">
                  <button className="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">
                    <a href="#">Demo</a>
                  </button>
                </div>
              </div>
              <div className="text-center  p-10  my-10  flex-1  rounded overflow-hidden shadow-lg  dark:bg-white mb-4">
                <Image className="w-full" src={weather} alt="Snappy" />
                <div className="px-6 py-4">
                  <div className="flex items-center text-yellow-600 justify-center font-bold font-burtons text-xl mb-2">
                    Weather app
                  </div>
                  <p className="text-gray-700 text-base">
                    A weather application made using html,css and javascript
                    that utilizes the{" "}
                    <a
                      href="https://openweathermap.org/"
                      className="text-red-500 underline"
                    >
                      openweather API
                    </a>{" "}
                    to give realtime weather information of searched location(s)
                    and renders a background image related to the searched
                    location.
                  </p>
                </div>
                <div className="px-6 pt-4 pb-2">
                  <button className="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">
                    <a href="#">Demo</a>
                  </button>
                </div>
              </div>
              <div className="text-center  p-10  my-10  flex-1  rounded overflow-hidden shadow-lg  dark:bg-white mb-4">
                <Image className="w-full" src={data} alt="Scrapped data" />
                <div className="px-6 py-4">
                  <div className="flex items-center text-yellow-600 justify-center font-bold font-burtons text-xl mb-2">
                    Web scrapper
                  </div>
                  <p className="text-gray-700 text-base">
                    Web scrapper application built with javescript(nodeJs) that
                    scraps countries' 3-letter code names and returns them in a
                    json file with country-code name key pair values
                  </p>
                </div>
                <div className="px-6 pt-4 pb-2">
                  <button className="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">
                    <a href="#">Demo</a>
                  </button>
                </div>
              </div>
            </div>
          </div>

          <motion.div
            className="box px-6 pt-4 mt-5 h-4 pb-2 flex justify-center items-center"
            whileHover={{ scale: 1.1 }}
            transition={{ type: "spring", stiffness: 400, damping: 10 }}
          >
            {" "}
            <button className="w-full mb-4 lg:w-6/12 bg-gradient-to-tr from-gray-800 to-yellow-600 hover:bg-yellow-600 text-white font-bold hover:text-black py-2 px-4 border border-yellow-600 hover:border-transparent rounded">
              View more projects
            </button>
          </motion.div>
        </section>
        <section>
          <h3 className=" flex justify-center items-center text-3xl py-1 mt-5">
            Tools and technologies
          </h3>

          <ParallaxText baseVelocity={-15}>HTML</ParallaxText>
          <ParallaxText baseVelocity={-15}>CSS</ParallaxText>
          <ParallaxText baseVelocity={-15}>JavaScript</ParallaxText>
          <ParallaxText baseVelocity={-15}>TailwindCss</ParallaxText>
          <ParallaxText baseVelocity={-15}>Bootstrap</ParallaxText>
          <ParallaxText baseVelocity={-15}>Reactjs</ParallaxText>
          <ParallaxText baseVelocity={-15}>Expressjs</ParallaxText>
          <ParallaxText baseVelocity={-15}>Git</ParallaxText>
          <ParallaxText baseVelocity={-15}>Typescript</ParallaxText>
          <ParallaxText baseVelocity={-15}>MySql & mongodb</ParallaxText>
        </section>
      </main>
    </>
  );
}
